### ISSUE TITLE
Issue with <label> tag

### ISSUE THREAD

**Issue by akshaybabloo** [timcreative/bootstrap-wizard#3]
Hi,

It looks like there is a typo at https://github.com/timcreative/bootstrap-wizard/blob/master/index.html#L134.

It should be `<label>Street Name</label>` not `<labe>Street Name</label>`; `l` is missing.

**Comment by alexandru-paduraru** [comment]
@akshaybabloo thank you for the information. We just updated it.

Best,
Alex
